FROM node:16 AS build

WORKDIR /usr/app

COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:16-alpine

WORKDIR /usr/app

COPY --from=build /usr/app ./

ENTRYPOINT ["npm","run", "start"]   
